[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
    Secure-Referrer-Policy = "origin-when-cross-origin"

[[edge_functions]]
  function = "hello" 
  path = "/hello"
